### ISSUE TITLE
module for handling assertions and creating a session

### ISSUE THREAD

**Issue by zaach** [mozilla/picl-server#1]
We'll expose a route for receiving assertions from clients. It'll verify the assertion and create a new session where the user's ID is the email.

Assume for now that the client audience is the data server.

**Comment by rfk** [comment]
Linking to the tokenserver API docs for ideas/reference:

  https://docs.services.mozilla.com/token/apis.html

There are complications that we'll bump into sooner or later around account provisioning, e.g. checking for acceptance of ToS and Privacy Policy.  But let's ignore those for now in favour of a quick prototype.

**Comment by rfk** [comment]
(FWIW I think that tokenserver's use of GET+Authz-Header worked out a little awkward in practice, POST+JSON-body would likely be a better fit with other myfx apis)

**Comment by almet** [comment]
@rfk ah? I'm interested to have more feedback on that, can you explicit a bit?

**Comment by rfk** [comment]
@ametarieau I'm not sure I can even put my finger on it, just something about using GET+Authz-Header seemed slightly wonky to me each time I coded against that API, like "this doesn't fit my brain quite right".  A trivial thing, not even worth bikeshedding about on existing code, but worth noting here.

**Comment by zaach** [comment]
Token-auth has been merged.
