### ISSUE TITLE
server periodically locks up, hangs all requests

### ISSUE THREAD

**Issue by rfk** [mozilla/picl-server#42]
We've observed this a couple of times: the dev server will periodically lock up and start hanging all incoming requests.  Nothing in the error log.  Restarting the server fixes the problem.

**Comment by zaach** [comment]
@seanmonstar mentioned that it occurs after he tries to sync bookmarks. It doesn't occur for him locally running memory db, so it might have to do with couchbase.

**Comment by rfk** [comment]
One idea: maybe our persistent connection to couchbase is timing out or otherwise getting stuck.

We should try spinning up a fresh connection on every method call and see if that makes a difference.  If that fixes the problem, then we need to either dig deeper into the couchbase module's connection handling or just implement our own pooling logic on top of it.

As a first step I've added {debug: true} to the couchbase config, which might get us some more output in the dbeug log to see what's going on.

**Comment by rfk** [comment]
Something like https://github.com/mozilla/picl-server/pull/43

**Comment by zaach** [comment]
#43  has been deployed. Now we wait...

**Comment by rfk** [comment]
It's locked up again, but here's a clue:

```
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
11891 app       20   0  739m  28m 6536 R 99.4  1.7 296:23.68 node
```

So something appears to be busy-looping the event loop...

**Comment by seanmonstar** [comment]
Yea, the connection just hangs when I make a request, which tells me
res.end() is never called. If the function had erred, or crashed, node
would have dumped and killed the connection...

**Comment by rfk** [comment]
I tried giving the process a SIGUSER1 and connecting to it from the debugger, but I wasn't able to execute any debugger commands - it appeared that the debugger was also hung.  May need a node guru to advise on next steps here...

Client folks, can you suggest a procedure for triggering this hang?

**Comment by rfk** [comment]
As far as we can tell, this lockup is occurring in the couchbase client lib itself.  We're going to push forward with an alternative storage backend for now, but will leave this bug open and look into it again at a later date.

**Comment by rfk** [comment]
Couchbase has been purged from the codebase, we don't need this no more.
