### ISSUE TITLE
Seperate database server

### ISSUE THREAD

**Issue by zaach** [mozilla/picl-server#54]
We'll need to split things up as we build up our scalable architecture. Should we have separate dbwriter and dbreader servers that we route requests to, like Persona?

**Comment by rfk** [comment]
For reference, we didn't do a reader/writer split for sync, IIRC because there weren't obvious security or scalability benefits.  We should definitely re-visit that question though.

**Comment by zaach** [comment]
Seems like the cloud deployment takes care of this.
