### ISSUE TITLE
Wiki changes

### ISSUE THREAD

**Issue by ghost** [mozilla/picl-server#79]
FYI: The following changes were made to this repository's wiki:

- defacing spam has been removed

- the wiki has been disabled, as it was not used

These were made as the result of a recent automated defacement of publically writeable wikis.

**Comment by vladikoff** [comment]
@rfk we should probably archive this repo :)

**Comment by ghost** [comment]
> @rfk we should probably archive this repo :)

treating that as a request -- repo archived (it can easily be reversed if need be).
